[2024-10-02T12:38:55.235+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_pipeline.test_task manual__2024-10-02T12:38:53.956434+00:00 [queued]>
[2024-10-02T12:38:55.247+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_pipeline.test_task manual__2024-10-02T12:38:53.956434+00:00 [queued]>
[2024-10-02T12:38:55.248+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-10-02T12:38:55.264+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): test_task> on 2024-10-02 12:38:53.956434+00:00
[2024-10-02T12:38:55.272+0000] {standard_task_runner.py:57} INFO - Started process 136 to run task
[2024-10-02T12:38:55.282+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_pipeline', 'test_task', 'manual__2024-10-02T12:38:53.956434+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/published_data_dag.py', '--cfg-path', '/tmp/tmp039xg25j']
[2024-10-02T12:38:55.286+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask test_task
[2024-10-02T12:38:55.390+0000] {task_command.py:415} INFO - Running <TaskInstance: test_pipeline.test_task manual__2024-10-02T12:38:53.956434+00:00 [running]> on host addf1b8c90fb
[2024-10-02T12:38:55.526+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Biokpor Solomon' AIRFLOW_CTX_DAG_ID='test_pipeline' AIRFLOW_CTX_TASK_ID='test_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T12:38:53.956434+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-02T12:38:53.956434+00:00'
[2024-10-02T12:38:55.737+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/published_data_dag.py", line 15, in download_using_xpath
    tree = html.fromString(response.content)
AttributeError: module 'lxml.html' has no attribute 'fromString'
[2024-10-02T12:38:55.755+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=test_pipeline, task_id=test_task, execution_date=20241002T123853, start_date=20241002T123855, end_date=20241002T123855
[2024-10-02T12:38:55.772+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 21 for task test_task (module 'lxml.html' has no attribute 'fromString'; 136)
[2024-10-02T12:38:55.810+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-02T12:38:55.834+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
