[2024-09-27T10:26:52.320+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_jd_pipeline.jdsport_pandas manual__2024-09-27T10:26:46.443176+00:00 [queued]>
[2024-09-27T10:26:52.331+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_jd_pipeline.jdsport_pandas manual__2024-09-27T10:26:46.443176+00:00 [queued]>
[2024-09-27T10:26:52.331+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-27T10:26:52.345+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): jdsport_pandas> on 2024-09-27 10:26:46.443176+00:00
[2024-09-27T10:26:52.353+0000] {standard_task_runner.py:57} INFO - Started process 69 to run task
[2024-09-27T10:26:52.359+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_jd_pipeline', 'jdsport_pandas', 'manual__2024-09-27T10:26:46.443176+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/jdsports_dag.py', '--cfg-path', '/tmp/tmpnrw43edy']
[2024-09-27T10:26:52.372+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask jdsport_pandas
[2024-09-27T10:26:52.448+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_jd_pipeline.jdsport_pandas manual__2024-09-27T10:26:46.443176+00:00 [running]> on host 304a62aaae75
[2024-09-27T10:26:52.587+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Biokpor Solomon' AIRFLOW_CTX_DAG_ID='etl_jd_pipeline' AIRFLOW_CTX_TASK_ID='jdsport_pandas' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T10:26:46.443176+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-27T10:26:46.443176+00:00'
[2024-09-27T10:26:52.591+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/jdsports_pipeline.py", line 4, in jdsports_pipeline
    use_pandas()
  File "/opt/airflow/etls/jdsports_etl.py", line 5, in use_pandas
    df = pd.read_json('/opt/airflow/fastfashion/jdsport.json')
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/json/_json.py", line 804, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1014, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1040, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1173, in parse
    self._parse()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1366, in _parse
    ujson_loads(json, precise_float=self.precise_float), dtype=None
ValueError: Trailing data
[2024-09-27T10:26:52.609+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_jd_pipeline, task_id=jdsport_pandas, execution_date=20240927T102646, start_date=20240927T102652, end_date=20240927T102652
[2024-09-27T10:26:52.626+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task jdsport_pandas (Trailing data; 69)
[2024-09-27T10:26:52.652+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-27T10:26:52.679+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
