[2024-09-27T10:28:38.273+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_jd_pipeline.jdsport_pandas manual__2024-09-27T10:28:31.952192+00:00 [queued]>
[2024-09-27T10:28:38.286+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_jd_pipeline.jdsport_pandas manual__2024-09-27T10:28:31.952192+00:00 [queued]>
[2024-09-27T10:28:38.286+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-27T10:28:38.304+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): jdsport_pandas> on 2024-09-27 10:28:31.952192+00:00
[2024-09-27T10:28:38.310+0000] {standard_task_runner.py:57} INFO - Started process 78 to run task
[2024-09-27T10:28:38.314+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_jd_pipeline', 'jdsport_pandas', 'manual__2024-09-27T10:28:31.952192+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/jdsports_dag.py', '--cfg-path', '/tmp/tmpl1670t2h']
[2024-09-27T10:28:38.317+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask jdsport_pandas
[2024-09-27T10:28:38.389+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_jd_pipeline.jdsport_pandas manual__2024-09-27T10:28:31.952192+00:00 [running]> on host 304a62aaae75
[2024-09-27T10:28:38.523+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Biokpor Solomon' AIRFLOW_CTX_DAG_ID='etl_jd_pipeline' AIRFLOW_CTX_TASK_ID='jdsport_pandas' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T10:28:31.952192+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-27T10:28:31.952192+00:00'
[2024-09-27T10:28:38.528+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/jdsports_pipeline.py", line 4, in jdsports_pipeline
    use_pandas()
  File "/opt/airflow/etls/jdsports_etl.py", line 5, in use_pandas
    df = pd.read_json('/opt/airflow/fastfashion/jdsport.json', lines=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/json/_json.py", line 804, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1012, in read
    obj = self._get_object_parser(self._combine_lines(data_lines))
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1040, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1173, in parse
    self._parse()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1366, in _parse
    ujson_loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2024-09-27T10:28:38.544+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_jd_pipeline, task_id=jdsport_pandas, execution_date=20240927T102831, start_date=20240927T102838, end_date=20240927T102838
[2024-09-27T10:28:38.560+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task jdsport_pandas (Expected object or value; 78)
[2024-09-27T10:28:38.570+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-27T10:28:38.603+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
